# Basic Site Settings
locale                   : "en-US"
site_theme               : "default"
title                    : "Shengwei Liu / Academic Portfolio"
title_separator          : "-"
name                     : &name "Shengwei Liu"
description              : &description "M.Eng. ECE @ Cornell Tech | B.Eng. EEE @ UCL | Researcher in Wearable Tech, Distributed Systems, and Computer Architecture"
url                      : "https://academicpages.github.io"  # If you keep sl3597 as username, change this to https://sl3597.github.io
baseurl                  : "" 
repository               : "sl3597/ShengweiLiu.github.io"   # Replace with your actual repo name

# Site Author
author:
  avatar           : "profile.png"
  name             : "Shengwei Liu"
  pronouns         : "he/him"
  bio              : "M.Eng. student at Cornell Tech (ECE 2026) and B.Eng. First-Class Honors graduate from UCL. Researching wearable bio-signal systems, CXL-enabled distributed memory, and microarchitecture reverse engineering."
  location         : "New York, USA"
  employer         : "Cornell Tech, Tsinghua University, University College London"
  uri              : "https://shengweiliu.github.io"
  email            : "sl3597@cornell.edu"

  # Academic websites
  googlescholar    : # Add once you have a profile
  orcid            : # Add once you register
  researchgate     : # Optional
  scopus           : # Optional

  # Repositories
  github           : "sl3597"

  # Social media
  linkedin         : "shengwei127"
  twitter          : # Optional
  instagram        : # Optional

# Publication Category
publication_category:
  books:
    title: 'Books'
  manuscripts:
    title: 'Journal Articles'
  conferences:
    title: 'Conference Papers'

# Site Settings
teaser                   : 
breadcrumbs              : false
words_per_minute         : 160
future                   : true
read_more                : "disabled"
talkmap_link             : false

# Analytics (optional)
analytics:
  provider               : "false"

# Conversion
markdown: kramdown
highlighter: rouge
